### ISSUE TITLE
[Task 7] LikeList tests handle case where user2 does not like user1

### ISSUE THREAD

**Issue by navarhontes** [CSC207-2023Y-UofT/course-project-tindar#56]

**Comment by jenniferjinyoungyang** [comment]
This was resolved by https://github.com/CSC207-2023Y-UofT/course-project-tindar/pull/26. 

![image](https://github.com/CSC207-2023Y-UofT/course-project-tindar/assets/76457965/ddb6f841-e443-4748-ad7c-5e3b2283095e)

![image](https://github.com/CSC207-2023Y-UofT/course-project-tindar/assets/76457965/4146fd0e-6df6-40e4-a25d-d7b2666a1dad)
