### ISSUE TITLE
[Feature 6] Navigate to View Profile or View Chat

### ISSUE THREAD

**Issue by candidcalcifer** [CSC207-2023Y-UofT/course-project-tindar#6]
User will be able to navigate from the match list to the profile page or the chat screen for a person in the match list.

**Comment by jenniferjinyoungyang** [comment]
It was decided only to navigate to chat not the profile from the match list. 

Navigating to chat will be handled in the issue https://github.com/CSC207-2023Y-UofT/course-project-tindar/issues/2.
